### ISSUE TITLE
getWallets() doesn't show all available wallets

### ISSUE THREAD

**Issue by Figumari** [DePayFi/web3-wallets#26]
Am I misunderstanding something or am I doing something wrong?
When I call the `getWallets()` method, shouldn't it list all the wallets that are available? In my example, I'm using the method on a website that I opened with Microsoft Edge. In Edge, I have installed and configured extensions for MetaMask, Phantom, and Trust Wallet. Now it should list these three wallets for me, right? But what I receive is the following:

```
[
    {
        "name": "Phantom",
        "logo": "data:image/svg+xml;base64,",
        "blockchains": [
            "ethereum",
            "polygon"
        ]
    },
    {
        "name": "Phantom",
        "logo": "data:image/svg+xml;base64,",
        "blockchains": [
            "solana"
        ]
    }
]
```

The same thing happens on your [demo page](https://depayfi.github.io/web3-wallets/demo.html).
Am I misunderstanding the method or is something not working here?

Thank you very much for your help and best regards.

**Comment by Figumari** [comment]
Addition: It seems to have something to do with the Phantom Wallet. When I uninstall this, the other wallets appear.

**Comment by 0xNe0x1** [comment]
Hi @Figumari 

multiple active wallet browser extensions do not work!

also see metamasks post about this topic: https://support.metamask.io/hc/en-us/articles/12174759849371-How-to-use-multiple-MetaMask-wallets#:~:text=Can%20I%20have%20multiple%20types,of%20them%20will%20work%20correctly.

the reason why this happens is that those extensions overwrite each other making it impossible to connect to them reliably (they are all competing for window.ethereum).

there is a new standard coming called „providerMap“ which allows to have multiple wallet browser extensions in parallel, but currently this only works with metamask + coinbase wallet extension.

in your case we recommend you only have 1 wallet browser extension available at the same time.

**Comment by 0xNe0x1** [comment]
We constantly update this library if wallets add providerMap capabilities. It could be that metamask+trust wallet is another combination that already works.

**Comment by Figumari** [comment]
Thank you for the clarification. That answers my question. 👍
