### ISSUE TITLE
Using @depay/web3-wallets with remix.run

### ISSUE THREAD

**Issue by arefay** [DePayFi/web3-wallets#8]
Similar to this issue: [https://github.com/DePayFi/widgets/issues/62](https://github.com/DePayFi/widgets/issues/62) which had an available work-around to use the bundled import...

I'm unable to use / import @depay/web3-wallets in my remix.run app, showing the error
<img width="775" alt="Screen Shot 2022-08-17 at 1 00 29 PM" src="https://user-images.githubusercontent.com/4808749/185199257-b4c24d0f-8e54-418d-addc-0007923d92e1.png">

I tried using this import

`import DePayWallets from "@depay/web3-wallets/dist/umd/index.js";`

but still gives this:
<img width="611" alt="Screen Shot 2022-08-17 at 1 00 00 PM" src="https://user-images.githubusercontent.com/4808749/185199156-5632efb4-c7ab-4d66-b3e9-859d3410a46e.png">

**Comment by 10xSebastian** [comment]
https://remix.run/docs/en/v1/guides/constraints#third-party-module-side-effects

There is no value in putting effort into supporting a JS server rendering technology for payment widgets or underlying libraries that are only intended to ever work on a client, in a browser and are impossible to render on a server 🤷

I think you are better off to use something else than remix at this point, or to load the widgets and underlying libraries via `<script>` tags to avoid remix altogether.
